apiVersion: v1
kind: Pod
metadata:
  name: restarting-pod
  labels:
    app: my-app
spec:
  containers:
  - name: restarting-container
    image: ubuntu:22.04
    command: ["/bin/bash", "-c", "count=0; while [ $count -lt 5 ]; do date; sleep 5; ((count+=1)); done; exit 3"]
