apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  namespace: default
  labels:
    app: load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      nodeSelector:
        node: node1
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - load
              topologyKey: kubernetes.io/hostname
      containers:
      - name: load
        image: ubuntu:22.04
        command: ["bash", "-c", "while true; do base64 -w 99 /dev/urandom | head -2000; sleep 1; done"]

