#!/bin/bash

export AWS_REGION=us-east-1

read -p "update? " update

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ $update = "Y" ]  || [ $update = "y" ]; then
    read -p "access key id " AWS_ACCESS_KEY_ID
    read -p "secret access key " AWS_SECRET_ACCESS_KEY

    rm $SCRIPT_DIR/creds
    echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > $SCRIPT_DIR/creds
    echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $SCRIPT_DIR/creds
fi

. $SCRIPT_DIR/creds

alias tf="$SCRIPT_DIR/run_tf.sh"

function clean() {
    read -p "Delete state files? y/n" -n 1 -r
    echo
    if [ $REPLY == "y" ]; then
        rm -f terraform.tfstate*
    fi
}

function cd_and_remove_terraform() {
  for dir in * ; do
    if [ -d $dir ]; then
        if [[ -d "$dir/.terraform" ]]; then
            echo "Removing $dir.terraform directory"
            sudo rm -rf "$dir/.terraform"
        else
            cd "$dir"
            cd_and_remove_terraform
            cd ..
        fi
    fi
  done
}

function new_configuration() {
    name=$1
    if [ -z "$name" ]; then echo "Enter name"; return; fi

    mkdir $name; cd $name

    cat << EOF > main.tf
terraform {
    required_providers {
        aws = {
            source = "hashicorp/aws"
            version = "~> 5.76"
        }
    }
}

provider "aws" {}
EOF

}
