apiVersion: v1
kind: Pod
metadata:
  name: memory-consumer
spec:
  containers:
  - name: memory-consumer
    image: yoavklein3/stress:0.2
    env:
      - name: "SIZE"
        value: "1000"
      - name: "PERCENT"
        value: "80"
    resources:
      limits:
        memory: "1Gi"  # Set memory limit for the pod

